theme: jekyll-theme-minimal
title: Sheng-Chieh Lin
description: PHD Student at the University of Waterloo
logo: https://media-exp1.licdn.com/dms/image/C5103AQG8ZtBYRx67DQ/profile-displayphoto-shrink_400_400/0/1544342511873?e=1634774400&v=beta&t=jPxcvJDWQsUUQVU9acfWDlHkucetiqbDGFrEjBdm2SI
show_downloads: false
